version: '3'
#docker container run -d --name postgres1 --network bridge2 -v psql-data:/var/lib/postgresql/data postgres:9.6.1
#docker container run -d --name postgres1 --network bridge2 -v psql-data2:/var/lib/postgresql/data postgres:9.6.2
#docker network create bridge2
#docker volume create psql-data
#docker volume create psql-data2

services:
  postgres1:
    image: postgres:9.6.1
    volumes:
      - psql-data:/var/lib/postgresql/data

  postgres2: postgres:9.6.2
    volumes:
      - psql-data2:/var/lib/postgresql/data

volumes:
  psql-data:
  psql-data2:
