version: '3'

services:
  drupal:
    image: drupal:latest
    ports:
      - '8080:80'
    volumes:
      - drupal_vol_modules:/var/www/html/modules
      - drupal_vol_profiles:/var/www/html/profiles
      - drupal_vol_sites:/var/www/html/sites
      - drupal_vol_themes:/var/www/html/themes


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword
   

volumes:
  drupal_vol_modules:
  drupal_vol_profiles:
  drupal_vol_sites:
  drupal_vol_themes:
